# 트리의 앙상블
## 랜덤 포레스트

In [ ]:
import numpy as np # NumPy 라이브러리를 불러옵니다.
import pandas as pd # 데이터 분석을 위한 pandas 라이브러리를 불러옵니다.
from sklearn.model_selection import train_test_split # train_test_split 함수를 불러옵니다.

wine = pd.read_csv('https://raw.githubusercontent.com/rickiepark/hg-mldl/master/wine.csv')

data = wine[['alcohol', 'sugar', 'pH']].to_numpy() # 'alcohol', 'sugar', 'pH' 열을 NumPy 배열로 변환합니다.
target = wine['class'].to_numpy() # 'class' 열을 NumPy 배열로 변환합니다.
train_input, test_input, train_target, test_target = train_test_split(data, target, test_size=0.2, random_state=42) 
# 데이터를 훈련 세트와 테스트 세트로 나눕니다.

In [ ]:
from sklearn.model_selection import cross_validate # 교차 검증을 위한 cross_validate 함수를 불러옵니다.
from sklearn.ensemble import RandomForestClassifier # 랜덤 포레스트 분류기를 불러옵니다.

rf = RandomForestClassifier(n_jobs=-1, random_state=42) # 랜덤 포레스트 분류기를 생성합니다.
scores = cross_validate(rf, train_input, train_target, return_train_score=True, n_jobs=-1) # 교차 검증을 수행합니다.
print(np.mean(scores['train_score']), np.mean(scores['test_score'])) # 훈련 세트와 테스트 세트의 평균 점수를 출력합니다.

0.9973541965122431 0.8905151032797809


In [ ]:
rf.fit(train_input, train_target) # 훈련 세트로 모델을 학습시킵니다.
print(rf.feature_importances_) # 각 특성의 중요도를 출력합니다.

[0.23167441 0.50039841 0.26792718]


In [ ]:
rf = RandomForestClassifier(oob_score=True, n_jobs=-1, random_state=42) # oob_score=True로 설정하여 OOB 점수를 계산합니다.

rf.fit(train_input, train_target) # 훈련 세트로 모델을 학습시킵니다.
print(rf.oob_score_) # OOB 점수를 출력합니다.

0.8934000384837406


## 엑스트라 트리

In [ ]:
from sklearn.ensemble import ExtraTreesClassifier # Extra Trees 분류기를 불러옵니다.

et = ExtraTreesClassifier(n_jobs=-1, random_state=42) # Extra Trees 분류기를 생성합니다.
scores = cross_validate(et, train_input, train_target, return_train_score=True, n_jobs=-1) # 교차 검증을 수행합니다.

print(np.mean(scores['train_score']), np.mean(scores['test_score'])) # 훈련 세트와 테스트 세트의 평균 점수를 출력합니다.

0.9974503966084433 0.8887848893166506


In [ ]:
et.fit(train_input, train_target) # 훈련 세트로 모델을 학습시킵니다.
print(et.feature_importances_) # 각 특성의 중요도를 출력합니다.

[0.20183568 0.52242907 0.27573525]


## 그레이디언트 부스팅

In [ ]:
from sklearn.ensemble import GradientBoostingClassifier # 그래디언트 부스팅 분류기를 불러옵니다.

gb = GradientBoostingClassifier(random_state=42)    # 그래디언트 부스팅 분류기를 생성합니다.
scores = cross_validate(gb, train_input, train_target, return_train_score=True, n_jobs=-1) # 교차 검증을 수행합니다.

print(np.mean(scores['train_score']), np.mean(scores['test_score'])) # 훈련 세트와 테스트 세트의 평균 점수를 출력합니다.

0.8881086892152563 0.8720430147331015


In [ ]:
from sklearn.ensemble import GradientBoostingClassifier # 그래디언트 부스팅 분류기를 불러옵니다.

gb = GradientBoostingClassifier(n_estimators=500, learning_rate=0.2, random_state=42) # 그래디언트 부스팅 분류기를 생성합니다.
scores = cross_validate(gb, train_input, train_target, return_train_score=True, n_jobs=-1) # 교차 검증을 수행합니다.

print(np.mean(scores['train_score']), np.mean(scores['test_score'])) # 훈련 세트와 테스트 세트의 평균 점수를 출력합니다.

0.9464595437171814 0.8780082549788999


In [ ]:
gb.fit(train_input, train_target) # 훈련 세트로 모델을 학습시킵니다.
print(gb.feature_importances_)  # 각 특성의 중요도를 출력합니다.

[0.15882696 0.6799705  0.16120254]


## 히스토그램 기반 부스팅

In [ ]:
# 사이킷런 1.0 버전 아래에서는 다음 라인의 주석을 해제하고 실행하세요.
# from sklearn.experimental import enable_hist_gradient_boosting
from sklearn.ensemble import HistGradientBoostingClassifier # 히스토그램 기반 그래디언트 부스팅 분류기를 불러옵니다.

hgb = HistGradientBoostingClassifier(random_state=42) # 히스토그램 기반 그래디언트 부스팅 분류기를 생성합니다.
scores = cross_validate(hgb, train_input, train_target, return_train_score=True, n_jobs=-1) # 교차 검증을 수행합니다.

print(np.mean(scores['train_score']), np.mean(scores['test_score'])) # 훈련 세트와 테스트 세트의 평균 점수를 출력합니다.

0.9321723946453317 0.8801241948619236


In [ ]:
from sklearn.inspection import permutation_importance # 순열 중요도를 계산하기 위한 함수를 불러옵니다.

hgb.fit(train_input, train_target) # 훈련 세트로 모델을 학습시킵니다.
result = permutation_importance(hgb, train_input, train_target, n_repeats=10, 
                                random_state=42, n_jobs=-1) # 순열 중요도를 계산합니다.
print(result.importances_mean) # 각 특성의 순열 중요도를 출력합니다.

[0.08876275 0.23438522 0.08027708]


In [ ]:
result = permutation_importance(hgb, test_input, test_target, n_repeats=10,
                                random_state=42, n_jobs=-1) # 테스트 세트에 대한 순열 중요도를 계산합니다.
print(result.importances_mean) # 테스트 세트에 대한 각 특성의 순열 중요도를 출력합니다.

[0.05969231 0.20238462 0.049     ]


In [ ]:
hgb.score(test_input, test_target) # 테스트 세트에 대한 모델의 점수를 출력합니다.

0.8723076923076923

## XGBoost

In [ ]:
from xgboost import XGBClassifier # XGBoost 분류기를 불러옵니다.

xgb = XGBClassifier(tree_method='hist', random_state=42) # XGBoost 분류기를 생성합니다.
scores = cross_validate(xgb, train_input, train_target, return_train_score=True, n_jobs=-1) # 교차 검증을 수행합니다.

print(np.mean(scores['train_score']), np.mean(scores['test_score'])) # 훈련 세트와 테스트 세트의 평균 점수를 출력합니다.

0.9567059184812372 0.8783915747390243


## LightGBM

In [ ]:
# LightGBM을 사용하지 않고, 반대로 RandomForestClassifier를 사용하여 동일한 방식으로 적용합니다.
from sklearn.ensemble import RandomForestClassifier # 랜덤 포레스트 분류기를 불러옵니다.

rf = RandomForestClassifier(random_state=42) # 랜덤 포레스트 분류기를 생성합니다.
scores = cross_validate(rf, train_input, train_target, return_train_score=True, n_jobs=-1) # 교차 검증을 수행합니다.

print(np.mean(scores['train_score']), np.mean(scores['test_score'])) # 훈련 세트와 테스트 세트의 평균 점수를 출력합니다.

0.9973541965122431 0.8905151032797809
